# conda env create -f environment.yml
name: ts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - statsmodels
  - holidays
  - lightgbm
  - pyarrow
  - pmdarima
  - pip