activation: gelu
alias: null
attn_dropout: 0.15
batch_normalization: true
batch_size: 64
dataloader_kwargs: null
drop_last_loader: false
dropout: 0.3
early_stop_patience_steps: -1
encoder_layers: 8
exclude_insample_y: false
fc_dropout: 0.3
futr_exog_list: null
h: 1
h_train: 1
head_dropout: 0.15
hidden_size: 512
hist_exog_list: null
inference_input_size: 90
inference_windows_batch_size: 2048
input_size: 90
learn_pos_embed: true
learning_rate: 5.0e-05
linear_hidden_size: 1024
loss: !!python/object:neuralforecast.losses.pytorch.MAE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: true
lr_scheduler: null
lr_scheduler_kwargs: null
max_steps: 10000
n_heads: 64
n_samples: 100
n_series: 1
num_lr_decays: 3
optimizer: null
optimizer_kwargs: null
patch_len: 64
random_seed: 42
res_attention: true
revin: true
revin_affine: true
revin_subtract_last: true
scaler_type: standard
start_padding_enabled: true
stat_exog_list: null
step_size: 1
stride: 24
training_data_availability_threshold: 0.0
val_check_steps: 50
valid_batch_size: null
valid_loss: null
windows_batch_size: 2048
